# Generated by Django 4.1.1 on 2022-11-21 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('V', 'Vinculado'), ('T', 'Trancado'), ('F', 'Formado')], max_length=2, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situações',
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicioSemestre', models.PositiveIntegerField(verbose_name='Semestre de ingresso')),
                ('fimSemestre', models.PositiveIntegerField(blank=True, null=True, verbose_name='Semestre de conclusão')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.curso')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.situacao', verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Vínculo',
                'verbose_name_plural': 'Vínculos',
                'ordering': ['-fimSemestre'],
            },
        ),
    ]
