# Generated by Django 4.1.1 on 2022-11-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacao',
            name='estado',
            field=models.CharField(choices=[('Vinculado', 'Vinculado'), ('Trancado', 'Trancado'), ('Formado', 'Formado')], max_length=20, verbose_name='Situação'),
        ),
    ]
